export default {
    "QuickInfo_CurVer": "Current version:",
    "Further_Reading_Head": "Recommended",
    "QuickInfo_BetaVer": "Beta version:",
    "Messenger_H1": "Instant messenger for corporate networks",
    "Close_Button": "Close",
    "Start_H1": "Welcome to vypress.com",
    "Solutions_H1": "VyPRESS Solution",
    "PR_Buy": "purchase",
    "QuickInfo_ClientPlatform": "Client Platforms:",
    "Start_Highlights": "Highlights",
    "Lanetis_Promo_Text": "&lt;strong&gt;Novell NetWare Revisor&lt;/strong&gt; is one of the best programs for administering and restoring NetWare servers. It can get and store server's image, create HTML-reports, view connected users, restore catalogues' structure and access rights for them, as well as many other things.",
    "Auvis_H1": "Auvis: One way messages receiver for network-wide alerts",
    "Start_LatestVersions": "Latest versions",
    "Support_H1": "Services &amp;amp; Support",
    "Newsletter_Intro": "Are you interested in hearing the latest from VyPRESS Research? From product updates to useful tips for getting the most out of our products? If so, it is easy to stay informed. Send us your e-mail address and we will keep you posted!",
    "PR_Download": "download",
    "Chat_H1": "LAN chat and text conferencing in easiest way with Vypress Chat",
    "Start_WelcomeImg": "/img/start/welcometo.gif",
    "NWSend_H1": "NWSend: send and receive Novell NetWare messages",
    "Start_BetaVersions": "Beta versions",
    "Start_Slogan": "Real-time messaging for real-time business&amp;trade;",
    "QuickInfo_Protocols": "Supported protocols:",
    "ClickToEnlarge": "Click to enlarge",
    "Tonecast_H1": "Tonecast: high quality radio broadcast over a local area network",
    "QuickInfo_Title": "Quick Info",
    "Newsletter_Header": "Newsletter",
    "QuickInfo_ServerPlatform": "Server Platforms:",
    "Newsletter_Button": "Subscribe",
    "Start_WelcomeTo": "Welcome to",
    "FooterBackToTop": "back to top",
};
