export default {
    "QuickInfo_CurVer": "Текущая версия:",
    "Further_Reading_Head": "Дополнительные материалы",
    "Recommended_Header": "Рекомендуем",
    "QuickInfo_BetaVer": "Предварительная версия:",
    "Messenger_H1": "Vypress Messenger: обмен сообщениями для корпоративных сетей",
    "Close_Button": "Закрыть",
    "Start_H1": "Добро пожаловать на vypress.com!",
    "Solutions_H1": "Решения VyPRESS",
    "QuickInfo_ClientPlatform": "Поддерживаемые &lt;acronym title=\"Операционные системы\"&gt;ОС&lt;/acronym&gt;:",
    "Start_Highlights": "Новости",
    "Lanetis_Promo_Text": "&lt;strong&gt;Novell NetWare Revisor&lt;/strong&gt; &amp;mdash; это превосходная программа для обслуживания серверов NetWare. Она позволяет получать и хранить образ сервера, просматривать подключенных пользователей и открытые ими файлы, конструировать и создавать HTML-отчеты, восстанавливать структуру каталогов на сервере и права на них, а также многое другое.",
    "Auvis_H1": "Auvis: Программа для оперативного оповещения в корпоративных сетях",
    "Start_LatestVersions": "Текущие версии",
    "Support_H1": "Техническая поддержка",
    "Newsletter_Intro": "Хотите быть в курсе всех обновлений и новых версий наших продуктов? Подпишитесь на наш ежемесячный список рассылки, и Вы будете получать уведомления о новых версиях, полезные советы по использованию наших продуктов и информацию о скидках.",
    "Chat_H1": "Vypress Chat: общение по сети и текстовые конференции",
    "Start_WelcomeImg": "img/texts/welcometo.png",
    "NWSend_H1": "NWSend: программа для обмена сообщения по сетям  Novell NetWare",
    "Start_BetaVersions": "Предварительные версии",
    "QuickInfo_Protocols": "Поддерживаемые протоколы:",
    "ClickToEnlarge": "Щёлкните, чтобы увеличить",
    "QuickInfo_Title": "Кратко",
    "Newsletter_Header": "Новости",
    "QuickInfo_ServerPlatform": "Поддерживаемые сервера:",
    "Newsletter_Button": "Подписаться",
    "Start_WelcomeTo": "Добро пожаловать",
    "FooterBackToTop": "вверх страницы",
};